POST http://localhost:3000/api/reservations/table HTTP/1.1
Content-Type: application/json

{
  "number": 5,
  "zone": "Zona B",
  "capacity": 8
}


###
POST http://localhost:3000/api/reservations/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZWQ3ZDQyNTAzMjQ4MTYxNGUwY2ZjOSIsImVtYWlsIjoiaXZhbi5tYXJ0aW5lekBsaXZlLnUtdGFkLmNvbSIsImdyYWRlIjoiSU5TTyIsInJvbCI6InVzZXIiLCJpYXQiOjE3NDM2MTczNzcsImV4cCI6MTc0NDIyMjE3N30.BidgmXeIr0-01n4scWTSUPQsktZWbT1mL4-aC8iSQ-w

{
  "table": "67ed851c52c706fedab5db7d",
  "project": "67c4eec663b8a52d1b5b2217",
  "date": "2024-04-05",
  "startTime": "16:00",
  "endTime": "18:00"
}
