GET https://surviving-poppy-sasahershko-72589d6b.koyeb.app/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzU4MTBjMWZhYjBmY2U3MzM3ODRmYyIsImVtYWlsIjoiYWRtaW5AdS10YWQuY29tIiwiZ3JhZGUiOiJudWxsIiwicm9sIjoiYWRtaW4iLCJpYXQiOjE3NDM0MTExOTAsImV4cCI6MTc0NDAxNTk5MH0.TTOY7jkBzp7sh-TlcLKx2U9kkKQbO3VOb1QFsQNKbZg
